# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:year/:month/:day/:title 

# Setup
title:            Brad Teller
tagline:          'Random Musings'
description:      ''
url:              http://bradteller.com
baseurl:          '/'
paginate:         3
