# Dependencies
markdown:         kramdown
highlighter:         rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Brad Teller
tagline:          'Random Musings'
description:      ''
url:              http://bradteller.com
baseurl:          '/'
paginate:         3
safe: true
lsi: false
theme: jekyll-theme-midnight