# Dependencies
markdown:         kramdown
highlighter:         rouge
kramdown:
  input: GFM

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Brad Teller
tagline:          'Random Musings'
description:      ''
url:              http://bradteller.com
baseurl:          '/'
paginate:         3
